language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --dev
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script: ./vendor/bin/tester ./tests